name: Continuous build using OMV

on:
  push:
    branches: [ master, development ]
  pull_request:
    branches: [ master, development ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.12" ] # Only test >=py3.9 as brian2 only supports that
        engine: [ jNeuroML ]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python  ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version:  ${{ matrix.python-version }}

    - name: Install OMV
      run: |
        pip install git+https://github.com/OpenSourceBrain/osb-model-validation
        
    - name: Run OMV tests
      run: |
        omv all -V
        omv list -V # list installed engines
